name: print-name

on:
  push:
    branches:
      - main
  workflow_dispatch:  # <-- should be under 'on'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print your name
        run: echo "Hello from GitHub Actions!"
